name: periodic-post

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "*/5 * * * *"
    
jobs:
  periodic-post:
    runs-on: ubuntu-latest
    permissions:
     actions: write
     checks: write
     contents: write
     deployments: write
     issues: write
     packages: write
     pull-requests: write
     repository-projects: write
     security-events: write
     statuses: write
    steps:
      - uses: actions/checkout@v3
      - name: Update apt Package lists
        run: sudo apt update -y
      - name: Upgrade apt version
        run: sudo apt upgrade -y
      - name: Pre-install LFS
        run: sudo apt-get install git-lfs
      - name: Install LFS
        run: git lfs install
      - name: Confirm LFS version
        run: git lfs --version
      - name: Enable LFS
        uses: actions/checkout@v3
        with:
          lfs: true
          clean: false
      - name: Register user email
        run: git config --global user.email "uho02741358@gmail.com"
      - name: Register user name
        run: git config --global user.name "Uchida16104"
      - name: Move directory
        run: cd ./articles
      - name: Initialize Git
        run: git init
      - name: Set current datetime as env variable
        uses: actions/checkout@v2
        env:
          TZ: 'Asia/Tokyo'
      - name: Start to set
        run: echo "---" > ${*}.md
      - name: Set title
        run: echo "title:　11¥ \"periodic post\"" >> ${*}.md
      - name: Set topics
        run: echo "topics:　11¥ [\"GitHubActions\",\"Qiita\",\"Zenn\",\"YAML\",\"bot\"]" >> ${*}.md
      - name: Set whther it can publish
        run: echo "published:　11¥ true" >> ${*}.md
      - name: Finish to set
        run: echo "---" >> ${*}.md
      - name: Write 1st comment
        run: echo "Hello world!" >> ${*}.md
      - name: Write 2nd comment
        run: echo "This is a periodic post." >> ${*}.md
      - name: Register files
        run: git add .
      - name: Commit files
        run: git commit -m "Upload Zend framework 3 skeleton" -m "Use GitHub web GUI"
      - name: Update files
        uses: stefanzweifel/git-auto-commit-action@v4
      - name: Push files
        run: git push --force-with-lease origin main
      - name: "Publish to Qiita"
        uses: noraworld/github-to-qiita@v1.0.1
        with:
          dir: "articles"
          qiita_access_token: d3565315000485b27c7787c3e34b67c2845ac184
          strict: false
